
language: python

python:
  - 3.2
  - 3.3
  - 3.4
  - pypy3

install:
    - sudo add-apt-repository ppa:webupd8team/java -y
    - sudo apt-get update
    - sudo apt-get install oracle-java8-installer
    - sudo update-java-alternatives -s jdk-8-oracle-x64
    - pip install scrutinizer-ocular coverage webtest httmock requests ppp_datamodel ppp_core jsonrpclib-pelix nltk
    - echo "y
        y
        y
        " | python -m nltk.downloader wordnet

before_script:
  - ./dependencies.sh
  - ./setup.py install

script:
  - rm ppp_questionparsing_grammatical* -rf
  - coverage3 run run_tests.py

after_script:
  - ocular --data-file ".coverage"
