
language: python

python:
  - 3.2
  - 3.3
  - 3.4
  - pypy3

install:
    - pip install scrutinizer-ocular coverage webtest httmock requests ppp_datamodel ppp_core jsonrpclib-pelix nltk
    - echo "y
        y
        y
        " | python -m nltk.downloader wordnet

before_script:
  - ./dependencies.sh
  - ./setup.py install

script:
  - coverage3 run run_tests.py

after_script:
  - ocular --data-file ".coverage"
